spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://mysql:3306/bci?serverTimezone=GMT%2b8
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: nacos:8848
      config:
        server-addr: nacos:8848

  redis:
    host: redis
    port: 6379
  session:
    store-type: redis