version: '3'
services:
  mysql:
    image: mysql:8
    container_name: bci-mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      - 13306:3306
    volumes:
      - ./mysql-data:/var/lib/mysql
      - ./mysql-config:/etc/mysql/conf.d
      - /etc/localtime:/etc/localtime:ro
      - ./mysql-init:/docker-entrypoint-initdb.d
    restart: always
    networks:
      - my-network

  redis:
    image: redis:6
    container_name: bci-redis
    ports:
      - 16379:6379
    volumes:
      - ./redis-data:/data
    restart: always
    networks:
      - my-network

  nacos:
    image: nacos/nacos-server:v2.2.0-slim
    container_name: bci-nacos
    environment:
      - MODE=standalone
      - PREFER_HOST_MODE=hostname
      - TZ=Asia/Beijing
    ports:
      - 8848:8848
      - 9848:9848
    volumes:
      - ./nacos-data:/home/nacos/data
    restart: always
    networks:
      - my-network

#  seata:
#    image: seataio/seata-server:1.4.2
#    container_name: bci-seata
#    volumes:
#      - ./seata-config:/seata-server/resources
#    restart: always
#    networks:
#      - my-network

networks:
  my-network:
