version: '3'
services:
  bci-gateway:
    container_name: bci-gateway
    build:
      context: ./bci-gateway
      dockerfile: Dockerfile
    ports:
      - "88:88"
    networks:
      - my-network

  bci-auth:
    build:
      context: ./bci-auth
      dockerfile: Dockerfile
    networks:
      - my-network

  bci-code:
    build:
      context: ./bci-code
      dockerfile: Dockerfile
    networks:
      - my-network

  bci-competition:
    build:
      context: ./bci-competition
      dockerfile: Dockerfile
    networks:
      - my-network

  bci-task:
    build:
      context: ./bci-task
      dockerfile: Dockerfile
    ports:
      - "9001:8083"
    networks:
      - my-network

networks:
  my-network:
