spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://10.112.39.8:3306/bci_test?serverTimezone=GMT%2b8
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 10.112.39.8:8848
      config:
        server-addr: 10.112.39.8:8848
  redis:
    host: 10.112.39.8
    port: 6379
  application:
    name: bci-scheduler


mybatis-plus:
  mapper-locations: classpath*:/mapper/*.xml
  global-config:
    db-config:
      id-type: auto
      logic-delete-value: 1
      logic-not-delete-value: 0
server:
  port: 15000

seata:
  enabled: true
  application-id: bci-scheduler
  # 事务组的名称，对应service.vgroupMapping.default_tx_group=xxx中配置的default_tx_group
  tx-service-group: default_tx_group
  # 配置事务组与集群的对应关系
  service:
    vgroup-mapping:
      # default_tx_group为事务组的名称，default为集群名称(与registry.conf中的一致)
      default_tx_group: default
    disable-global-transaction: false
  registry:
    type: nacos
    nacos:
      application: seata-server
      server-addr: 10.112.39.8:8848
      group: SEATA_GROUP
      username: nacos
      password: nacos
      # registry.conf中，配置cluster名称
      cluster: default
  config:
    type: nacos
    nacos:
      server-addr: 10.112.39.8:8848
      group: SEATA_GROUP
      username: nacos
      password: nacos
      # nacos配置中心配置的dataId
      data-id: seataServer.properties
