spring:
  datasource:
    username: root
    password: 151806
    url: jdbc:mysql://mysql-master-l7jd.bci-dev:3306/bci_task?serverTimezone=GMT%2b8
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: bci-nacos-5y5a.bci-dev:8848
      config:
        server-addr: bci-nacos-5y5a.bci-dev:8848

  redis:
    host: bci-redis-m0dz.bci-dev
    port: 6379
  session:
    store-type: redis

seata:
  enabled: true
  application-id: bci-scheduler
  # 事务组的名称，对应service.vgroupMapping.default_tx_group=xxx中配置的default_tx_group
  tx-service-group: default_tx_group
  # 配置事务组与集群的对应关系
  service:
    vgroup-mapping:
      # default_tx_group为事务组的名称，default为集群名称(与registry.conf中的一致)
      default_tx_group: default
    disable-global-transaction: false
  registry:
    type: nacos
    nacos:
      application: bci-seata
      server-addr: bci-nacos-5y5a.bci-dev:8848
      group: SEATA_GROUP
      username: nacos
      password: nacos
      # registry.conf中，配置cluster名称
      cluster: default
  config:
    type: nacos
    nacos:
      server-addr: bci-nacos-5y5a.bci-dev:8848
      group: SEATA_GROUP
      username: nacos
      password: nacos
      # nacos配置中心配置的dataId
      data-id: seataServer.properties