spring:
  application:
    name: bci-gateway
  config:
    import: nacos:bci-gateway.yml
  cloud:
    nacos:
      discovery:
        server-addr: 10.101.170.116:8848
      config:
        server-addr: nacos:8848
    gateway:
      routes:
        - id: auth_route
          uri: lb://bci-auth
          predicates:
            - Path=/auth/**
          filters:
            - RewritePath=/auth/(?<segment>/?.*), /auth/$\{segment}
        - id: auth_route
          uri: lb://bci-auth
          predicates:
            - Path=/team/**
          filters:
            - RewritePath=/team/(?<segment>/?.*), /team/$\{segment}

        - id: code_route
          uri: lb://bci-code
          predicates:
            - Path=/code/**
          filters:
            - RewritePath=/code/(?<segment>/?.*), /code/$\{segment}

        - id: competition_route
          uri: lb://bci-competition
          predicates:
            - Path=/event/**
          filters:
            - RewritePath=/event/(?<segment>/?.*), /event/$\{segment}

        - id: competition_route
          uri: lb://bci-competition
          predicates:
            - Path=/paradigm/**
          filters:
            - RewritePath=/paradigm/(?<segment>/?.*), /paradigm/$\{segment}

        - id: task_route
          uri: lb://bci-task
          predicates:
            - Path=/task/**
          filters:
            - RewritePath=/task/(?<segment>/?.*), /task/$\{segment}


server:
  port: 88
