spring:
  application:
    name: bci-file
  config:
    import: nacos:bci-file.yml
  cloud:
    nacos:
      discovery:
        server-addr: 10.101.166.103:18848
        ip: 10.112.6.9
      config:
        server-addr: 10.101.166.103:18848
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://10.101.166.103:13306/bci?useSSL=false&useUnicode=true&serverTimezone=Asia/Shanghai&characterEncoding=utf8
    username: root
    password: 123456
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 15
      minimum-idle: 5
      idle-timeout: 30000
  data:
    redis:
      host: 10.101.166.103
      port: 16379

server:
  port: 8084