# 应用名称
spring:
  application:
    name: bci-task
  datasource:
    username: root
    password: root
    url: jdbc:mysql://10.112.39.8:3306/bci_test?serverTimezone=GMT%2b8
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 10.112.39.8:8848
      config:
        server-addr: 10.112.39.8:8848
  redis:
    host: 10.112.39.8
    port: 6379
  session:
    store-type: redis

server:
  port: 8105
  servlet:
    session:
      timeout: 30m
mybatis-plus:
  mapper-locations: classpath*:/mapper/*.xml
  global-config:
    db-config:
      id-type: auto
      logic-delete-value: 0
      logic-not-delete-value: 1

logging:
  level:
    com.hcc.task: debug


dataset: 1

image:
  scoreUrl: IP=10.112.5.184
  names: bci-ssvep:v1.0, bci-mi:v1.0, bci-erp:v1.0, bci-turing:v1.0, bci-attack:v1.0, bci-emotion:v1.0

task:
  names: ssvep, mi, erp, turing, attack, emotion

container:
  maxTime: 10, 10, 10, 10, 10, 10
  cmd: python main.py
  codePath: /workdir

map:
  hostUrls: /nfs/data/${dataset}/ssvep, /nfs/data/${dataset}/mi, /nfs/data/${dataset}/erp, /nfs/data/${dataset}/turing, /nfs/data/${dataset}/attack, /nfs/data/${dataset}/emotion
  containerUrls: /workdir/TestData/SSVEP, /workdir/TestData/MI, /workdir/TestData/RSVP

commit:
  maxCount: 2

collection:
  image: collection:v1.0
  srate: 250
  nchan: 9
  timebuffer: 0.04


online:
  kafkaIp: 10.112.120.252
  codePath: /workdir/AlgorithmImplement

seata:
  enabled: true
  application-id: bci-task
  # 事务组的名称，对应service.vgroupMapping.default_tx_group=xxx中配置的default_tx_group
  tx-service-group: default_tx_group
  # 配置事务组与集群的对应关系
  service:
    vgroup-mapping:
      # default_tx_group为事务组的名称，default为集群名称(与registry.conf中的一致)
      default_tx_group: default
    disable-global-transaction: false
  registry:
    type: nacos
    nacos:
      application: seata-server
      server-addr: 10.112.39.8:8848
      group: SEATA_GROUP
      username: nacos
      password: nacos
      # registry.conf中，配置cluster名称
      cluster: default
  config:
    type: nacos
    nacos:
      server-addr: 10.112.39.8:8848
      group: SEATA_GROUP
      username: nacos
      password: nacos
      # nacos配置中心配置的dataId
      data-id: seataServer.properties
