spring:
  application:
    name: bci-task
  config:
    import: nacos:bci-task.yml
  cloud:
    nacos:
      discovery:
        server-addr: nacos-svc.bci2024:8848
      config:
        server-addr: nacos-svc.bci2024:8848

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql-node.bci2024:3306/bci?useSSL=false&serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 15
      minimum-idle: 5
      idle-timeout: 30000
  data:
    redis:
      host: redis-svc.bci2024
      port: 6379



bci:
  token:
    timeout: 100
    timeUnit: SECONDS

server:
  port: 8083
