# 应用名称
spring:
  application:
    name: bci-code
  datasource:
    username: root
    password: root
    url: jdbc:mysql://10.112.39.8:3306/bci_test?serverTimezone=GMT%2b8
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 10.112.39.8:8848
      config:
        server-addr: 10.112.39.8:8848
  redis:
    host: 10.112.39.8
    port: 6379
  cache:
    type: redis
    redis:
      time-to-live: 60000
      cache-null-values: true
  session:
    store-type: redis

#端口
server:
  port: 8000
  servlet:
    session:
      timeout: 30m


#代码保存路径
code:
  url: "C:/Users/13016/Desktop/上传文件"


mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
      logic-delete-value: 1
      logic-not-delete-value: 0

logging:
  level:
    com.hcc.code: debug

seata:
  enabled: true
  application-id: bci-code
  # 事务组的名称，对应service.vgroupMapping.default_tx_group=xxx中配置的default_tx_group
  tx-service-group: default_tx_group
  # 配置事务组与集群的对应关系
  service:
    vgroup-mapping:
      # default_tx_group为事务组的名称，default为集群名称(与registry.conf中的一致)
      default_tx_group: default
    disable-global-transaction: false
  registry:
    type: nacos
    nacos:
      application: seata-server
      server-addr: 10.112.39.8:8848
      group: SEATA_GROUP
      username: nacos
      password: nacos
      # registry.conf中，配置cluster名称
      cluster: default
  config:
    type: nacos
    nacos:
      server-addr: 10.112.39.8:8848
      group: SEATA_GROUP
      username: nacos
      password: nacos
      # nacos配置中心配置的dataId
      data-id: seataServer.properties